<footer style="position: fixed-bottom;">
<div class="container">
<div class="navbar navbar-static-bottom">
   
    <div class="row">
     <div class="col-xs-12">
      <div class="col-xs-12 col-sm-3 col-md-3 col-lg-4">
        
        <h4><img src="imagenes/icono2.png"> Contacto</h4>
          <ul class="list-unstyled">
            <li><i class="glyphicon glyphicon-envelope"></i> Correo: <a href="mailto:contacto@poolstore.com.uy">contacto@poolstore.com.uy</a></li>
            <li><i class="glyphicon glyphicon-earphone"></i> Teléfono: <a 
              href="intent://send/+59893901854#Intent;scheme=smsto;package=com.whatsapp;action=android.intent.action.SENDTO;end">Enviar WhatsApp</a></li>
            <li><i class="glyphicon glyphicon-phone"></i> Celular: <a href="tel:+59893901854">093 901 854</a></li>
            <li><i class="glyphicon glyphicon-modal-window"> </i><a href="#"> Contacto</a></li>
          </ul>
      </div>
      <div class="col-sm-6 footer-address">
        <h4>&nbsp;</h4>
        &nbsp;<br/>
        &nbsp;<br/>
        &nbsp;<br/>
       </div> 
      <div class="col-sm-6 footer-address">
        <h5>&nbsp;</h5>
         <a href="#"> fSP Diseño </a>
       </div>
      </div>
     </div>
   

  </div>
 </div>
 </footer>
